set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# very large history
set -g history-limit 1000000

set -g mouse on


# base settings
set -g clock-mode-style 12
set -g focus-events on
set -g history-limit 50000

set -g set-clipboard on


set -g status-style 'bg=default,fg=white' # transparent status bar
set -g pane-active-border-style "fg=green,bg=default"
set -g pane-border-style "fg=white,bg=default"
set -g window-status-format "#[fg=brightblack,bg=default](#[fg=white,bg=default]#I #F #W#[fg=brightblack,bg=default])"
set -g window-status-current-format "#[fg=brightblack,bg=default](#[fg=magenta,bold,bg=default]#I #F #W#[fg=brightblack,nobold,bg=default])"
set -g status-left-length 50
set -g status-left "#[fg=cyan,bold,bg=default] #S " # session name

set-option -g status-right '#(/usr/local/bin/tmux-mem --format ":currentBytes [#[fg=:color]:spark#[default]] #[fg=:color]:percent#[default]") #(/usr/local/bin/tmux-cpu --format ":load [#[fg=:color]:spark#[default]] #[fg=:color]:percent#[default]") %H:%M %d-%b-%y'
